name: Build
on: [push, pull_request]
jobs:
  Ubuntu_x86_64:
    runs-on: ubuntu-latest
    steps:
    - name: Set up system
      run: echo "Set up system"
    - name: Checkout
      uses: actions/checkout@main
    - name: Configure
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Package
      run: cmake --build ${{github.workspace}}/build/CLANG-prefix/src/CLANG-build --target package
    - name: Upload
      uses: actions/upload-artifact@main
      with:
        name: Ubuntu_x86_64
        path: ${{github.workspace}}/build/package/*.zip